name: smart_app
description: "Smart Home Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.243.0
  mqtt_client: ^10.8.0 
  fl_chart: ^0.64.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.1.2
  uuid: ^3.0.7
  lottie: ^2.6.0
  intl: ^0.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/curtain.json
